export const Packages = [
  {
    id: 1,
    title: 'Package 1',
    description: [
      '100–150 shots of the M Mobile Bar selection of shooters, shakers and flavors',
      '100–150 glasses of M Mobile Bar cocktails',
      'Tequila & syringe shots',
    ],
    inclusions: [
      'A set of lighted bar counters',
      'Presented by professional bartender',
      'On the spot cocktail mixing every drink serve',
      'Customized drink list',
      'Complete set of lighted bar counter, equipment and bar glasses',
    ],
    perks: [
      'A chance to have freebies if you survive our challenges',
      '3 to 4 good looking bouncers',
      'Free use of Laser Lights',
      'Free use of Tower',
      'Unlimited Time of service',
      "Free use of client's liquors",
    ],
    addOns: [
      'Welcome drink (non alcoholic) upon guest arrived',
      'Coffee and Tea',
      'Case of SMB lights',
      'Case of SMB pale pilsen',
      'Case of GSM pale pilsen',
      'Additional Bartender',
    ],
    price: '13,000',
    notes: 'Transportation may be charged in different areas price may change without prior notice',
  },
  {
    id: 2,
    title: 'Package 2',
    description: [
      '200–250 shots of the M Mobile Bar selection of shooters, shakers and flavors',
      '200–250 glasses of M Mobile Bar cocktails',
      'Tequila & syringe shots',
    ],
    inclusions: [
      'A set of lighted bar counters',
      'Presented by professional bartender',
      'On the spot cocktail mixing every drink serve',
      'Customized drink list',
      'Complete set of lighted bar counter, equipment and bar glasses',
    ],
    perks: [
      'A chance to have freebies if you survive our challenges',
      '3 to 4 good looking bouncers',
      'Free use of Laser Lights',
      'Free use of Tower',
      'Unlimited Time of service',
      "Free service of client's liquors",
    ],
    addOns: [
      'Welcome drink (non alcoholic) upon guest arrived',
      'Hot Coffee and Tea',
      'Case of SMB lights',
      'Case of SMB pale pilsen',
      'Case of GSM pale pilsen',
      'Additional Bartender',
    ],
    price: '15,500',
    notes: 'Transportation may be charged in different areas price may change without prior notice',
  },
];